config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'restaurants#index'

  get 'restaurants', to: 'restaurants#index'
  get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant
  post 'restaurants', to: 'restaurants#create'
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
  get 'restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant
  patch 'restaurants/:id', to: 'restaurants#update'
  delete 'restaurants/:id', to: 'restaurants#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrudVtt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<br>
<hr>
<%= link_to 'back to restaurants', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
    </li>
  <% end %>
</ul>

<br>
<hr>
<%= link_to 'create a new restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<br>
<hr>
<%= link_to 'back to restaurants', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<h2><%= @restaurant.address %></h2>

<h2>Rating: <%= '⭐' * @restaurant.rating %></h2>

<br>
<%= link_to 'edit restaurant', edit_restaurant_path(@restaurant) %>
<%= link_to "Delete",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<hr>
<%= link_to "back to restaurants", restaurants_path %>